name: Backend Golang CI

on:
  push:
    paths:
      - backend/golang/**
  pull_request:
    paths:
      - Backend/golang/**

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Env handle
        working-directory: ./Backend/golang
        run: cp env .env

      - name: Build
        working-directory: ./Backend/golang
        run: go build -v ./...

      - name: Test
        working-directory: ./Backend/golang
        run: go test -v ./...
